version: '3.8'
services:
  backend:
    build: ./backend
    env_file:
      - ../.env  # or './.env' if your .env is in the root
    environment:
      - DEBUG=true
      - NODE_ENV=development
    ports:
      - "3001:3001"
    volumes:
      - ./backend:/app 